In [12]:
import torch
import numpy as np
from torch.nn import functional as F
import time
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)

cuda


In [13]:
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()

total_time = end_time - start_time
print(f"total time taken is {total_time:4f}")

total time taken is 0.002002


In [14]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)


start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

total_time = end_time - start_time
print(f"total time taken is {total_time:4f}")

start_time = time.time()
rand = np.multiply(np_rand1,np_rand2)
end_time = time.time()
total_time = end_time - start_time
print(f"total time taken is {total_time:4f}")


total time taken is 0.252794
total time taken is 0.236403


C:\Users\anilk\AppData\Local\Temp\ipykernel_19292\4108718828.py:17: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1,np_rand2)


In [15]:

probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities,num_samples = 10,replacement = True)
print(samples)

tensor([1, 1, 1, 1, 1, 0, 1, 1, 1, 1])


In [16]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [17]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0,float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [20]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [22]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
tensor3 = torch.tensor([1,2,3])

stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [23]:
import torch.nn as nn
tensor1 = torch.tensor([10.,10.,10.])

linear = nn.Linear(3,3,bias = False)
print(linear(tensor1))

tensor([ 3.5051, 10.9212,  1.6950], grad_fn=<SqueezeBackward4>)


In [24]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])

softmax_op = F.softmax(tensor1,dim=0)


print(softmax_op)

tensor([0.0900, 0.2447, 0.6652])


In [25]:
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size,embedding_dim)


input_indices = torch.LongTensor([1,5,3,4])

embedded_output = embedding(input_indices)

print(embedded_output)
print(embedded_output.shape)


tensor([[-7.4242e-01, -5.2160e-01, -3.5719e-01,  5.2731e-01, -7.2512e-02,
          4.1002e-01],
        [ 1.8569e-04, -6.8872e-01,  3.8905e-01,  4.7915e-02, -1.1516e+00,
          5.4954e-01],
        [ 3.1278e-01,  3.9416e-02, -3.1182e-01, -9.9826e-01, -2.1013e+00,
          1.7845e-01],
        [ 2.0986e-01,  1.1292e-02,  8.5521e-02, -7.4759e-02, -6.2181e-01,
         -1.4545e+00]], grad_fn=<EmbeddingBackward0>)
torch.Size([4, 6])


In [26]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

#print(a @ b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [27]:
int_64 = torch.randint(10,(3,2)).float()

float_32 = torch.rand(2,3)

result = torch.matmul(int_64,float_32)

print(result)

tensor([[3.8542, 2.6989, 1.7109],
        [2.6100, 1.6102, 1.0083],
        [3.8947, 2.5098, 1.5786]])


In [28]:
a = torch.rand(2,3,5,2)
print(a)
print(a.shape)
x,y,z,k = a.shape
a=a.view(3,2,5,2)
print(a.shape)
print(a)

tensor([[[[0.7137, 0.3286],
          [0.0458, 0.2220],
          [0.5928, 0.1550],
          [0.9429, 0.5882],
          [0.3491, 0.5000]],

         [[0.5258, 0.9663],
          [0.2487, 0.3868],
          [0.2039, 0.9977],
          [0.1237, 0.4342],
          [0.0880, 0.8925]],

         [[0.5571, 0.1609],
          [0.5162, 0.3968],
          [0.5579, 0.9510],
          [0.1294, 0.8274],
          [0.4394, 0.1594]]],


        [[[0.4284, 0.3265],
          [0.0130, 0.8982],
          [0.6521, 0.5120],
          [0.5276, 0.6278],
          [0.0292, 0.3992]],

         [[0.2738, 0.7041],
          [0.3329, 0.0776],
          [0.6779, 0.9054],
          [0.9641, 0.4766],
          [0.2379, 0.1585]],

         [[0.0283, 0.5331],
          [0.2900, 0.5194],
          [0.1683, 0.1527],
          [0.6068, 0.9664],
          [0.4290, 0.5672]]]])
torch.Size([2, 3, 5, 2])
torch.Size([3, 2, 5, 2])
tensor([[[[0.7137, 0.3286],
          [0.0458, 0.2220],
          [0.5928, 0.1550],
          [

In [29]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [39]:
input = torch.rand((4,8,10))
B,T,C = input.shape
output = input.view(B*T,C)
print(input)
print(input[: , -1, :])

tensor([[[4.0906e-01, 9.8905e-01, 9.7289e-01, 4.5626e-01, 1.3887e-01,
          4.0484e-01, 5.1749e-01, 9.1866e-01, 6.1904e-01, 6.2683e-01],
         [1.0143e-02, 1.2837e-01, 9.1898e-01, 4.6229e-01, 4.7418e-01,
          4.0217e-01, 5.4540e-01, 3.2919e-01, 3.5856e-02, 5.1646e-01],
         [9.6916e-01, 2.8493e-02, 2.8151e-01, 3.5929e-01, 3.6002e-01,
          4.7966e-01, 8.8586e-01, 8.4955e-01, 2.8355e-01, 7.9304e-01],
         [1.2393e-01, 2.6759e-01, 2.0483e-01, 5.0680e-01, 3.3972e-01,
          4.8264e-01, 6.0337e-01, 9.4742e-01, 7.0099e-01, 4.5782e-01],
         [6.3460e-01, 1.7173e-01, 2.5433e-01, 7.6066e-01, 9.3791e-01,
          9.7019e-01, 2.1728e-01, 5.2109e-01, 9.6908e-01, 4.9441e-01],
         [4.4556e-01, 3.0273e-01, 4.9179e-01, 1.3559e-01, 5.8675e-01,
          5.5924e-01, 6.2172e-01, 9.6633e-01, 3.1392e-01, 8.6308e-01],
         [4.5452e-01, 9.1870e-01, 8.1102e-01, 6.8831e-01, 5.2093e-01,
          1.4316e-01, 1.9041e-01, 1.0735e-01, 8.9939e-01, 3.9538e-01],
         [3.5

In [42]:
x = torch.tensor([1],dtype = torch.float32)
y = F.tanh(x)
print(y)

tensor([0.7616])
